### ISSUE TITLE
Possible error in RoutingModule.cs

### ISSUE THREAD

**Issue by tinidk** [OsmSharp/OsmSharp.Service.Routing#9]
Hi

Just tried the service, and it would nok work until i changed line 144 from
if (!string.IsNullOrWhiteSpace(urlParameterRequest.loc))

to

if (string.IsNullOrWhiteSpace(urlParameterRequest.loc))

Best regards
Martin.

**Comment by xivk** [comment]
Ouwch that's not good. Can you post and example request?

**Comment by tinidk** [comment]
http://localhost:1234/kempen-big/routing?loc=51.261028637438386,4.780511856079102&loc=51.26795006429507,4.801969528198242&vehicle=car

Just the one from the examples

**Comment by xivk** [comment]
https://github.com/OsmSharp/OsmSharp.Service.Routing/blob/master/OsmSharp.Service.Routing/RoutingModule.cs#L144

You are correct!

**Comment by tinidk** [comment]
thax, and thanks for a great lib.
